version: "3.8"

services:
  backend: #fastapi 
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --reload
    depends_on:
      - db

  frontend: # Streamlit UI
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run frontend/Home.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - web

  db: # Postgres with pgvector
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
